In [122]:
import numpy as np
import pandas as pd

In [124]:
df = pd.read_csv('votes_training.csv')
df

Gender  Age  Education  State  Finances  Party
0          2   81          3     21         1      1
1          2   23          3      2         0      2
2          1   21          3     26         0      1
3          2   53          1      9         1      3
4          2   44          2     27         2      1
...      ...  ...        ...    ...       ...    ...
9995       1   66          0      4         0      2
9996       2   81          3     26         1      1
9997       2   64          1      2         0      1
9998       1   73          1     26         2      2
9999       1   55          3     20         2      1

[10000 rows x 6 columns]

In [145]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error, f1_score

In [126]:
model = LinearRegression()

In [127]:
x_train = df.iloc[:,:-1]
y_train = df.iloc[:,-1].values

In [128]:
model.fit(x_train,y_train)

LinearRegression()

In [129]:
df_test = pd.read_csv('votes_testing.csv')

In [130]:
x_test = df_test.iloc[:,:-1]
y_test = df_test.iloc[:,-1].values

In [131]:
y_pred = model.predict(x_test)
y_pred

array([1.65624615, 1.53084987, 1.57647006, 1.65370882, 1.58697934,
       1.72635241, 1.69989609, 1.65949605, 1.60853506, 1.64874165,
       1.66941691, 1.61221768, 1.65874867, 1.74901108, 1.53804853,
       1.49928266, 1.6681886 , 1.53632789, 1.72936   , 1.6820344 ,
       1.53685679, 1.58103107, 1.63082412, 1.70993479, 1.63791618,
       1.6620248 , 1.57420497, 1.61089624, 1.71888032, 1.69981132,
       1.71843107, 1.7546115 , 1.59775475, 1.61883652, 1.57957656,
       1.65916061, 1.68622339, 1.65724563, 1.75071856, 1.6425355 ,
       1.69683614, 1.70707093, 1.72534715, 1.50925477, 1.61326851,
       1.71373981, 1.63398091, 1.64665389, 1.65897694, 1.60058901,
       1.54099204, 1.58758581, 1.67589441, 1.61786326, 1.67827735,
       1.67895783, 1.68127178, 1.7432727 , 1.53314208, 1.75264365,
       1.61904923, 1.67049974, 1.63677579, 1.51871853, 1.72280774,
       1.60773707, 1.6272931 , 1.59854434, 1.68449209, 1.59519674,
       1.61236968, 1.72308695, 1.64391243, 1.71971224, 1.72583

In [132]:
error = y_pred - y_test
error

array([-0.34375385,  0.53084987,  0.57647006,  0.65370882,  0.58697934,
        0.72635241, -0.30010391, -0.34050395, -0.39146494, -0.35125835,
        0.66941691,  0.61221768, -0.34125133,  0.74901108,  0.53804853,
        0.49928266, -1.3318114 ,  0.53632789, -0.27064   ,  0.6820344 ,
        0.53685679,  0.58103107, -0.36917588, -1.29006521,  0.63791618,
       -0.3379752 , -0.42579503,  0.61089624,  0.71888032, -0.30018868,
       -0.28156893, -1.2453885 ,  0.59775475, -0.38116348,  0.57957656,
        0.65916061, -1.31377661, -0.34275437, -0.24928144,  0.6425355 ,
       -1.30316386, -0.29292907,  0.72534715, -0.49074523, -0.38673149,
        0.71373981,  0.63398091,  0.64665389, -0.34102306, -1.39941099,
        0.54099204, -0.41241419, -0.32410559,  0.61786326,  0.67827735,
        0.67895783,  0.68127178,  0.7432727 , -0.46685792,  0.75264365,
        0.61904923,  0.67049974, -0.36322421,  0.51871853, -0.27719226,
        0.60773707,  0.6272931 ,  0.59854434, -0.31550791, -0.40

In [135]:
r2 = r2_score(y_test, y_pred)
r2

0.010614559346739938

In [136]:
mse = mean_squared_error(y_test,y_pred)
mse

0.4307378560573626

## Trying hyperparameter tuning to improve accuracy

In [137]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [138]:
biased_randoms = 1 - np.random.rand(100) ** 2

param_grid = {'alpha':biased_randoms.tolist()}

In [139]:
ridge = Ridge()

In [140]:
grid = GridSearchCV(estimator=ridge, param_grid=param_grid, scoring='r2', cv=10)
grid.fit(x_train, y_train)

GridSearchCV(cv=10, estimator=Ridge(),
             param_grid={'alpha': [0.15558138741504723, 0.9986081377857204,
                                   0.3014651592633053, 0.9982295119224823,
                                   0.6978888923060903, 0.979032730897171,
                                   0.09300678502188897, 0.78408176940874,
                                   0.7862083714081103, 0.543698057827152,
                                   0.5429645732793942, 0.5944533427133165,
                                   0.489205812437579, 0.8648149232809449,
                                   0.9798203218786128, 0.35356962893458277,
                                   0.4320801449415076, 0.2594949025897859,
                                   0.8805080837222995, 0.7267240345408013,
                                   0.34520702016560867, 0.3523619627667308,
                                   0.45808425764395666, 0.7987125429730075,
                                   0.9848322590681572, 0.21315019934942525,
                                   0.9944757231379776, 0.6222834382913967,
                                   0.9384377578111226, 0.680673296404087, ...]},
             scoring='r2')

In [118]:
best_model = grid.best_estimator_
y_pred = best_model.predict(x_test)

In [141]:
grid.best_params_['alpha']

0.9999845548054171

In [148]:
f1_score(y_pred)

TypeError: missing a required argument: 'y_pred'

In [143]:
mean_squared_error(y_test,y_pred)

0.4307378560573626

In [189]:
from sklearn.linear_model import LogisticRegression

new_model = LogisticRegression(C=1, max_iter=100000)
new_model.fit(x_train,y_train)
y_pred = new_model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.54      0.73      0.62       479
           2       0.61      0.50      0.55       421
           3       0.00      0.00      0.00       100

    accuracy                           0.56      1000
   macro avg       0.38      0.41      0.39      1000
weighted avg       0.51      0.56      0.53      1000



C:\Users\tanrc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tanrc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tanrc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificati

In [169]:
error = y_pred - y_test
error

array([ 0,  0,  1,  0,  1,  1,  0, -1, -1,  0,  0,  1, -1,  0,  0,  0, -2,
        0,  0,  1,  0,  1, -1, -2,  0, -1,  0,  0,  0, -1,  0, -2,  0, -1,
        1,  0, -2,  0, -1,  0, -2,  0,  1,  0, -1,  1,  0,  1, -1, -2,  0,
       -1,  0,  1,  0,  1,  1,  1,  0,  1,  0,  0, -1,  0, -1,  0,  1,  0,
       -1,  0, -1,  0,  0,  1,  0, -1, -2,  0,  0, -1, -1,  0,  0,  0,  1,
        0,  0, -1,  0,  0, -1,  1,  0, -1,  0, -1,  1,  1,  0, -2,  1,  0,
        0,  1,  0,  0,  0,  0,  0, -2,  0, -2,  0,  0,  0, -1,  0, -2, -1,
       -1,  1,  0,  1,  0,  0,  1,  0,  0,  0,  1,  0, -1,  0, -2,  1,  0,
        1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1,  0,  1,  0, -1,  0, -2,
       -2, -2,  0,  1, -1, -1, -2,  0, -2, -1,  0,  1, -1, -1,  0,  1,  0,
        1, -1,  0,  0,  0, -2,  0,  0, -1,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  0, -1,  1,  0,  0, -1, -1,  0,  0, -2, -2, -1,  0, -1,  0,
        0,  0,  1,  0, -2,  0,  1,  0, -1,  0, -1,  0,  1, -2, -2,  0,  1,
        1,  0, -1,  1,  0

In [170]:
f1_score(y_test,y_pred,average='weighted')

0.5282438628314763

In [171]:
print(pd.Series(y_train).value_counts())

1    4956
2    3807
3    1237
Name: count, dtype: int64


In [172]:
model_fix_v1 = LogisticRegression(class_weight='balanced', max_iter=10000)
model_fix_v1.fit(x_train,y_train)
y_pred_fix_v1 = model_fix_v1.predict(x_test)

f1_score(y_test,y_pred, average='weighted')

0.5282438628314763

In [175]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

grid = GridSearchCV(LogisticRegression(max_iter=1000), param_grid, scoring='f1_weighted')
grid.fit(x_train, y_train)
print("Best F1:", grid.best_score_)
print("Best Params:", grid.best_params_)

Best F1: 0.5190207265705608
Best Params: {'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}


In [176]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           1       0.54      0.73      0.62       479
           2       0.61      0.50      0.55       421
           3       0.00      0.00      0.00       100

    accuracy                           0.56      1000
   macro avg       0.38      0.41      0.39      1000
weighted avg       0.51      0.56      0.53      1000



C:\Users\tanrc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tanrc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tanrc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificati

In [186]:
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Resample the training data
smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

# Train the model
model = LogisticRegression(max_iter=1000)
model.fit(x_train_resampled, y_train_resampled)

# Predict on the original test set
y_pred = model.predict(x_test)

# Evaluate
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.61      0.37      0.46       479
           2       0.61      0.64      0.62       421
           3       0.21      0.55      0.30       100

    accuracy                           0.50      1000
   macro avg       0.47      0.52      0.46      1000
weighted avg       0.57      0.50      0.51      1000



In [185]:
f1_score(y_test,y_pred, average='weighted')

0.5101144217208607